### PR TITLE
Compile with -O3, separate key expansion, and do not force allocations

### LINKED ISSUE #1: Poor performance. 8.58 - 9.45 cpb
Hey. I'm (gradually) implementing Sphinx and HORNET. I'll be using HCTR as my SPRP because it builds on normal primitives (`BC = AES-128, AXU = POLYVAL`), is simple and is sufficiently fast enough. I'm avoiding AEZ on the premise that its complex and intrusive design is unhealthy for implementations, but I decided to benchmark it as it was supposed to be quick and is an SPRP.

Recommendations:

1. Split out the AES key expansion, it is slow and can be reused. This may not matter for your use case as Loopix uses distinct paths per packet; but it makes AEZ look horrible to Rust consumers who find this crate.

2. Encrypt/decrypt in place. Allocating is slow, especially if you want to handle high loads and are interested in AEZ for its high performance.

```
throughput/aez-encrypt/1024
                        time:   [9642.0824 cycles 9680.5622 cycles 9718.7663 cycles]
                        thrpt:  [9.4910 cpb 9.4537 cpb 9.4161 cpb]
Found 5 outliers among 100 measurements (5.00%)
  5 (5.00%) high mild
throughput/aez-decrypt/1024
                        time:   [9654.9435 cycles 9695.2769 cycles 9736.5744 cycles]
                        thrpt:  [9.5084 cpb 9.4680 cpb 9.4287 cpb]
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
throughput/aez-encrypt/2048
                        time:   [18458.1809 cycles 18537.1270 cycles 18614.7876 cycles]
                        thrpt:  [9.0893 cpb 9.0513 cpb 9.0128 cpb]
throughput/aez-decrypt/2048
                        time:   [18457.0398 cycles 18541.9442 cycles 18625.2243 cycles]
                        thrpt:  [9.0943 cpb 9.0537 cpb 9.0122 cpb]
throughput/aez-encrypt/4096
                        time:   [35980.6519 cycles 36157.0494 cycles 36334.6163 cycles]
                        thrpt:  [8.8708 cpb 8.8274 cpb 8.7843 cpb]
throughput/aez-decrypt/4096
                        time:   [35602.2529 cycles 35758.1323 cycles 35921.9576 cycles]
                        thrpt:  [8.7700 cpb 8.7300 cpb 8.6920 cpb]
throughput/aez-encrypt/8192
                        time:   [70154.7788 cycles 70514.6029 cycles 70879.3800 cycles]
                        thrpt:  [8.6523 cpb 8.6077 cpb 8.5638 cpb]
throughput/aez-decrypt/8192
                        time:   [70397.5765 cycles 70727.0361 cycles 71055.9571 cycles]
                        thrpt:  [8.6738 cpb 8.6337 cpb 8.5935 cpb]
throughput/aez-encrypt/16384
                        time:   [139955.0308 cycles 140464.0862 cycles 140970.7971 cycles]
                        thrpt:  [8.6042 cpb 8.5732 cpb 8.5422 cpb]
throughput/aez-decrypt/16384
                        time:   [139951.4526 cycles 140577.4754 cycles 141218.4333 cycles]
                        thrpt:  [8.6193 cpb 8.5802 cpb 8.5420 cpb]
```

### PR DESCRIPTION
**Pull request by WildCryptoFox**
Nice and fast graph! Fixes #1!

I didn't touch serde, sorry, killed the test vectors. But now it is fast and has a nicer API. You can re-add the old encrypt/decrypt API for backwards compatibility if you care about that.

The criterion points at my fork, you'll want to swap it back once it is accepted. Or just swap it back to `WallTime` if you don't care about cpb.

hctr vs aez

### CODE REVIEW

**Comment by james-darkfox** [comment]
@david415 How do you feel about moving this into https://github.com/rustcrypto ?

**Comment by david415** [comment]
great work! i'll have to make the test vectors work with this... so that i can prove binary compatibility. i don't care about preserving the old api... i just want the test vectors to work.

**Comment by WildCryptoFox** [comment]
Added more test vectors.

AEZ supports vector AAD. The C implementation does not. The C comment at the top says "single AAD" yet the source appears to indicate "at most one AAD", as it treats a null pointer as no AAD.

12 of the test vectors pass. 1024 are skipped due to requiring vector AADs.

**Comment by WildCryptoFox** [comment]
The non-aesni reference supports vector AAD but provides a different interface and is only intended as a reference or toy, not for production code. Consumers of this crate must have x86/x86_64 hardware with AES support.

**Pull request merged**
